### ISSUE TITLE
Allow wildcards paths in controller.operators

### ISSUE THREAD

**Issue by dinana** [wprl/baucis#191]
When using $set operator on array fields sub elements it requires to include all indexes in controller.operators, i.e. controller.operators("$set", "arrayField.1 arrayField.2 arrayField.3 ..")
##

**Comment by wprl** [comment]
Move update operator functionality to a plugin in 2.x

**Comment by jjfattz** [comment]
This feature would be very valuable for me as well.

**Comment by wprl** [comment]
What do you guys think of the operators feature in general?  I'm deep into the coding for v2.x, and it might be worth reevaluating this feature.  

What use case do you have for it?  What operators do you use it with?  Do regexes solve the problem or is there something less hacky that would work better?  Is only allowing certain prescreened fields to be used more of an arbitrary restriction than a security feature?

If possible it would be good to implement special operations without using a custom header, like for example being able to POST to /api/resource/123/some.array.field that is automatically set up to do the `$push`.  I have not ended up using this feature much in production, so your thoughts around it would be very helpful.

**Comment by jjfattz** [comment]
For me, just simply being able to use a positional operator ($) would awesome.

For example:

Instead of this (what the OP mentioned above):
`controller.operators("$set", "arrayField.1 arrayField.2 arrayField.3 ...")`

We could do something like this:
`controller.operators("$set", "arrayField.$")`

That would at least cut down on having to specify many indexes manually for each path.

Thanks!
