### ISSUE TITLE
an error in example

### ISSUE THREAD

**Issue by zzswang** [wprl/baucis#215]
following code:

controller.request(function (request, response, next) {
  request.baucis.outgoing(through(function (context) {
    if (context.doc.owner !== request.user) {
      // Errors will be passed off to `next` later, and the stream will
      // be stopped.
      this.emit('error', baucis.errors.Forbidden());
      return;
    }
    **delete context.doc.password;**
    this.queue(context);
  }));
  next();
});

delete context.doc.password;

will not actually be executed.

I'm not sure why. but if 

``context.doc.password = 'undefined'``

it can work. but not perfect...

**Comment by wprl** [comment]
This is because context.doc is a Mongoose model.  Which disallows deleting properties.  Something that might be useful in other similar situations is to add a stream to run .toJSON() on each context doc as part of the outgoing stream.  I don't want to make this default since it may be useful to have the Mongoose document object with attached methods, etc.  Thanks for reporting!
