### ISSUE TITLE
Baucis differentiation

### ISSUE THREAD

**Issue by yieme** [wprl/baucis#228]
What do you see are the strengths or complements of [Baucis](http://kun.io/baucis) with other Rest API tools like [Sails JS](http://sailsjs.org/) and [StrongLoop](http://strongloop.com/)?

### What I'm seeing:

Area | Baucis | SailsJS | LoopBack
---- | ---- | ---- | ----
Meta Data |  [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS) & Swagger | Blueprint | Swagger
Express integration | Yes | Yes | Yes
Access Control List  | ? | Yes | Yes
Socket.io | ? | Yes | Coming
Open Source | Yes, July 2012 | Yes, January 2012 | Yes, April 2013
Commercial Backing | [Kun.io](http://kun.io/) | [Balderdash](http://balderdash.co/) | [StrongLoop](http://strongloop.com/)
ORM | Mongo centric? | Yes | Yes

### Community

Area | Baucis | SailsJS | LoopBack
---- | ---- | ---- | ----
Google <name> + "rest" | 7k results | 9k results | 67k results
Github stars / forks | 440 / 55 | 8,935 / 988 | 2,904 / 256

**Comment by wprl** [comment]
Yes, this is pretty accurate.  Baucis is more niche-focused than competitors.  It has two primary goals.

1) easily giving less experienced developers a way to instantly create "correct" HATEOAS REST APIs simply from defining Mongoose schemata. 

2) It also gives the flexibility to allow advanced developers a toolbox to create APIs with high performance, easy scalability, and rich query semantics.

Baucis embraces the Node.js philosophy of small, purpose-built, and pluggable modules.  We recommend using existing [Express middleware](https://www.npmjs.com/search?q=express+middleware) such as [node_acl](https://github.com/OptimalBits/node_acl), rather than relying on monolithic frameworks that seek to be all things to all people.

Baucis' answer to Socket.io is an in-the-works [SSE plugin](https://github.com/wprl/baucis-subscribe).  A [web hook plugin](https://github.com/wprl/baucis-hooks) is also in the design stage.

I'm going to close this since it isn't an issue per se, but feel free to ask any more questions!

**Comment by yieme** [comment]
@wprl, I like the NodeJS/*nux philosophy also. Thanks for the clarifications :-)
