### ISSUE TITLE
Trailers for chunked encoding

### ISSUE THREAD

**Issue by wprl** [wprl/baucis#241]
Enable Etag, LastModified for collection endpoints.  See response.addTrailers

**Comment by wprl** [comment]
Added in v1.1.0

**Comment by mmoulton** [comment]
I'm currently debugging a problem with IE 11 where it's failing to properly interpret the `Etag` and `Last-Modified` headers at the end of collection endpoints that was added in this enhancement. This is resulting in errors in IE such as: `XMLHttpRequest: Network Error 0x2ee4, Could not complete the operation due to error 00002ee4.`

While the problem is not with Baucis, it has led me to investigate the use of the `Trailers` header in baucis.

My research has found the while most browsers will happily parse the `Trailers` headers at the end of a `chunked` encoding, I have yet to find one that will actually use the values. It seems that unless the browsers initial request supplies the `TE: trailers` header in it's request, any response using a `Trailers` header becomes optional. So far Chrome 44, Safari 8 and FF 39 are failing to interpret the value of `Etag` and `Last-Modified` for any collection endpoint.

While I believe the Trailers approach you are using to properly calculate the `Etag` value is the ideal approach, I wonder if this is a case where the ideal scenario has not caught up to the reality of the browsers spec implementations.

Thoughts?

**Comment by wprl** [comment]
Interesting question. I had assumed it was supported by browsers because of the inclusion of the trailer feature in Express but haven't tested. I plan to do some testing of my own. I also wonder what proxy support for trailers is like…

I want to avoid buffering the whole response before sending it to calculate Etag which is why trailers are used here.
