### ISSUE TITLE
Support other databases?

### ISSUE THREAD

**Issue by timbur** [wprl/baucis#262]
@wprl I'm curious about how easy (or difficult) you would expect it to be to add the ability to swap out the database?  This is obviously not something I'm asking you to do, but upon first glance `baucis` seems designed intelligently enough that creating drivers for different databases wouldn't be too difficult, relatively speaking.  I love `baucis`'s design and I would like to use it with say, RethinkDB instead of MongoDB.  This isn't something I plan on doing any time soon though.  It's just something to consider.

**Comment by wprl** [comment]
I have a prototype of baucis working with MySQL.  It was surprisingly easy to change out the DB in most ways... I disabled a few features though, come to think of it.  

I haven't released it though since my resources to devote to maintaining it are limited.  But, if you or someone else were happy to maintain a plugin for RethinkDB or another DB, I'd be happy to help in any way I could!

**Comment by timbur** [comment]
Awesome!  I think the best approach would be to separate `mongoose` from `baucis` and then reincorporate it via some driver system.  What do you think?  I'm willing to do it when I get a chance, but I have no idea when that might be.

**Comment by wprl** [comment]
Yes, I think that's a good approach.  If anyone wants to see the MySQL code for reference just ping me.  

Thanks for your input!  Going to close since this isn't currently scheduled.
