### ISSUE TITLE
baucis shouldn't be a dependency of itself

### ISSUE THREAD

**Issue by fgnass** [wprl/baucis#274]
Since version 1.3 baucis [depends on itself](https://github.com/wprl/baucis/blob/master/package.json#L41) in package.json which is really ... awkward. If I understand it correctly, this is to satisfy the peer dependency defined by `baucis-links`.

In order to get rid of this cyclic reference and break out of dependency hell, I would like to suggest to:

1.  remove the [self-dependency](https://github.com/wprl/baucis/blob/master/package.json#L41)
2. remove the [require('baucis')](https://github.com/wprl/baucis-links/blob/master/middleware.js#L6) which isn't used.
3. drop the [peer dependency](https://github.com/wprl/baucis-links/blob/master/package.json#L17)

I think it's a good idea to follow [substack's recommendation](https://github.com/npm/npm/issues/5080#issuecomment-40549383) on plugins and not use peerDependencies for this at all. If a baucis plugin needs to access the baucis instance it could acquire it via the context (e.g. `this.baucis` or `req.baucis`).

As a result it would be possible again to do a `git clone ... && npm install && npm test` without errors and without having to fiddle with `npm link`.

**Comment by wprl** [comment]
I agree.  Especially point 1… that's just bizarre.  

baucis-links doesn't really need the peer dependency, since it's only used internally by baucis.  And that will definitely clean things up to do 2 & 3.  

I'm not sure it's wise to give up on peerDependency at the moment.  The changes in npm 3 sound like they will address much of the peerDependency weirdness.  Users were having version issues when the peerDependencies were not specified well.

**Comment by timbur** [comment]
:+1:
