### ISSUE TITLE
Problem with virtuals and controller.select

### ISSUE THREAD

**Issue by proswdev** [wprl/baucis#276]
I’m running into an issue using virtuals when combined with controller.select
With the following schema

var userSchema = new Schema({
    firstName: String,
    lastName: String,
    email: String
});

userSchema.set('toJSON', { virtuals: true });
userSchema.set('toObject', { virtuals: true });

userSchema
    .virtual('fullName')
    .get(function() {
        return this.firstName + ' ' + this.lastName;
    });

and baucis setup as follows:

var controller = baucis.rest(User);
// controller.select('-firstName -lastName');
app.use('/', baucis());

http://localhost/users will show the firstName, lastName and fullName properly, but when I uncomment the controller.select line, firstName and lastName are not shown (by design) but fullName will now display “undefined undefined”. 

It appears the controller.select method not only removes the fields from the output but also makes them no longer available to the model instance itself which breaks any virtuals that may depend on them. In this case, the firstName and lastName should be removed from the output so fullName can be shown instead. Any suggestions on how to can accomplish this with Baucis?

I’ve made a sample project based on the express generator that highlights this problem available on github at https://github.com/proswdev/baucistest.git.

**Comment by wprl** [comment]
Good question.  This could be more straightforward, or explained in the README.  This ticket should stay open until either of those two criteria are met.  Here's a brief summary:

`controller.select` sets the underlying Mongoose query select option, so this is expected behavior of Mongoose.  

The supported way to do this is to use an outgoing stream.  Perhaps you could use something like [stream-son](https://www.npmjs.com/package/stream-json).  Or, a basic example using a map function would be:

```javascript
controller.request(function (request, response, next) {
  request.outgoing(function (context, nextOutgoing) {
    context.doc = _.clone(context.doc);
    delete context.doc.xyz;
    nextOutgoing(null, context);
  });
});
```

Cheers,
William

**Comment by wprl** [comment]
Baucis2 will no longer support Mongoose, using native Mongo instead.
