### ISSUE TITLE
Investigate browser and proxy support for Etag trailer

### ISSUE THREAD

**Issue by wprl** [wprl/baucis#295]
See #241

**Comment by mmoulton** [comment]
Wanted to see if you were able to make any progress on this investigation?

As it stands right now, any collection endpoint from Baucis is not compatible with IE11 or below when accessed via AJAX due to this issue.

From my research, it's not yet reasonable to use the Trailers headers, as such it seems like a decision will have to be made to do one of the following:

* support a strong ETag / Last-Modified and buffer the response from mongo
* develop a weak ETag / Last-Modified substitute (not sure this is reasonable)
* drop ETag / Last-Modified support for collection endpoints

I'm currently running on a patched version, but I would love to have a proper solution upstream. I'd be more than happy to submit a PR if you let me know your thoughts on what direction you would like to see taken.

**Comment by wprl** [comment]
I'm more interested in writing a proxy or plugin for one that does support Etag (if one does not exist already) than disabling it completely.  That being said, we need to solve your immediate problem.  I think the best solution for the moment would be to add an option to turn off Etag Trailers or Trailers entirely. Would this solve the IE issues for you?

**Comment by mmoulton** [comment]
This will solve the issue for me, yes. Currently I'm running on a patched branch that simply removes the support entirely (https://github.com/mmoulton/baucis). If you make this a configurable option, I would happily move back to the main line branch.

Thanks!

**Comment by lcalvy** [comment]
Hi, 

You can also test with browserstack and local tunneling, proxy seems to have issue with Trailer headers. 
On chrome 46, AJAX request fail randomly. On server side everthing is ok.

**Comment by wprl** [comment]
Browsers don't support Etag trailers, I found out through a series of communications elsewhere.  This functionality will be implemented with HTTP/2 header frames.
