### ISSUE TITLE
Query string parameters: conditions filter date

### ISSUE THREAD

**Issue by tom-heyvaert** [wprl/baucis#314]
I am trying to filter my records between two timestamps using $gt and $lt using the following query:
`{'timestamp':{'$gt':'2016-12-14T18:00:00.000Z','$lt':'2016-12-14T18:40:00.000Z'}}`
When I try this query in Robomongo it returns the desired results.
However when I add this query to the query string parameter conditions and do a request. 
It returns the entire collection.
`api/beacons?conditions="{%27timestamp%27:{%27$gt%27:%272016-12-14T18:00:00.000Z%27,%27$lt%27:%272016-12-14T18:40:00.000Z%27}}"`

Thanks in advance

**Comment by pjmolina** [comment]
Hi Tom.
Pleas try:
`
api/beacons?conditions={%27timestamp%27:{%27$gt%27:%272016-12-14T18:00:00.000Z%27,%27$lt%27:%272016-12-14T18:40:00.000Z%27}}
`
 instead of

`
api/beacons?conditions="{%27timestamp%27:{%27$gt%27:%272016-12-14T18:00:00.000Z%27,%27$lt%27:%272016-12-14T18:40:00.000Z%27}}"
`

The enclosing quotes `"` around the `conditions` are not needed in baucis.

**Comment by tom-heyvaert** [comment]
Thank you for the quick response.

By leaving the enclosing `"` out and replacing the `'`(%27-url encoded) with `"`(%22-url encoded) I got it to work.

Thanks for the quick response!

**Comment by pjmolina** [comment]
True also, baucis (JSON parser in this case) only allows double quotes instead of simple ones.
