### ISSUE TITLE
Routes returning 404 with Mongose v > 5.0.2

### ISSUE THREAD

**Issue by mathurs** [wprl/baucis#329]
I set up a basic example with express and latest mongoose and the routes generated via baucis are returning 404. Changed mongoose version back to 4.13.8, and the routes work fine. Could be a regression with mongoose, as this is a recently released version.

Thanks,
Saurabh

**Comment by wprl** [comment]
Thanks for reporting this. Mongoose 5 is not currently supported, however I’m happy to accept PRs to add compatibility.

**Comment by maxiejbe** [comment]
Hi guys! 

I got mongoose 5 working: https://github.com/maxiejbe/baucis/tree/improvement/mongoose-5-compatibility. Basically I fixed:

**Pluralize**
`var pluralize = require('mongoose/lib/utils').toCollectionName;` was not working as expected. 
I supplied an external pluralize function from https://github.com/blakeembrey/pluralize.

```
var pluralizeFn = require('pluralize');
model.plural(pluralize(model.singular(), pluralizeFn));
```
**Query.stream() instead of Query.cursor()**
```
pipeline(request.baucis.query.stream()); // findOne do not support cursor
```
was used for findOne operation instead of:
```
pipeline(request.baucis.query.cursor());
```
I think that's not possible in mongoose 5 (Cursor works as expected). This change might break backwards compatibility.

Could you please take a look  @wprl? I can make a PR later :+1: 
Thanks

**Comment by maxiejbe** [comment]
No problem @wprl :+1: 
I'm off until February 9, will DM you then!
Thanks!

**Comment by ivanhuay** [comment]
I had the same problem. I tried to update baucis but it was easier to do something else inspired by baucis. That's why I decided to create [hiroki](https://github.com/ivanhuay/hiroki).
It has some differences but it may be useful if you want to use the latest version of mongoose.

**Comment by DebVortex** [comment]
@wprl @maxiejbe how is the situation regarding this topic? Would be glad to see mongoose 5 support in baucis. Did you two find a way to still check for the pullrequest even with the contract work?

**Comment by maxiejbe** [comment]
@DebVortex Here is the PR: https://github.com/wprl/baucis/pull/335. 
This is my first time contributing to Baucis (and my fix was really quick), so I would like someone else to review it before merging. 
I don't really know the project enough to be the mantainer or approve others PRs.
What do you suggest @wprl?
Thanks
